# Name for this GitHub Actions workflow
name: Generate Video

# This allows you to run the workflow manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  build:
    # Use a standard Ubuntu Linux virtual machine to run the job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code so the runner can access it
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install the Python libraries your script needs
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python numpy

      # Step 4: Run your Python script to generate the video
      - name: Run video generation script
        run: python create_video.py

      # Step 5: Upload the generated video as a downloadable "artifact"
      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-video # The name of the downloadable file collection
          path: blood_types_video.mp4 # The name of the file to upload
